-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 14:31:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_sharas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_sharas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sharas` DEFAULT CHARACTER SET latin1 ;
USE `bd_sharas` ;

-- -----------------------------------------------------
-- Table `bd_sharas`.`pasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`pasto` (
  `pasto_id` INT NOT NULL,
  `pasto_num` INT(11) NULL,
  `pasto_status` INT NULL,
  `pasto_desc` VARCHAR(120) NULL,
  PRIMARY KEY (`pasto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`endereco` (
  `endereco_id` INT NOT NULL,
  `endereco_numero` VARCHAR(45) NULL,
  `endereco_cep` INT(11) NULL,
  `endereco_rua` VARCHAR(80) NULL,
  `endereco_bairro` VARCHAR(80) NULL,
  `endereco_cidade` VARCHAR(80) NULL,
  `endereco_estado` VARCHAR(80) NULL,
  PRIMARY KEY (`endereco_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`cliente` (
  `cliente_id` INT NOT NULL,
  `cliente_nome` VARCHAR(80) NULL,
  `cliente_endereco` INT NULL,
  `cliente_email` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id`),
  INDEX `cliente_endereco_idx` (`cliente_endereco` ASC) VISIBLE,
  CONSTRAINT `cliente_endereco`
    FOREIGN KEY (`cliente_endereco`)
    REFERENCES `bd_sharas`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`criador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`criador` (
  `criador_id` INT NOT NULL,
  `criador_nome` VARCHAR(80) NULL,
  `criador_email` VARCHAR(45) NULL,
  `criador_endereco` INT NULL,
  PRIMARY KEY (`criador_id`),
  INDEX `criador_endereco_idx` (`criador_endereco` ASC) VISIBLE,
  CONSTRAINT `criador_endereco`
    FOREIGN KEY (`criador_endereco`)
    REFERENCES `bd_sharas`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`animal` (
  `animal_id` INT NOT NULL,
  `animal_nome` VARCHAR(80) NULL,
  `animal_registro` VARCHAR(45) NOT NULL,
  `animal_criador` INT NULL,
  `animal_nasc` DATE NULL,
  `animal_sexo` VARCHAR(45) NULL,
  `animal_pelagem` VARCHAR(45) NULL,
  `animal_proprietario` INT NULL,
  `animal_local` INT NULL,
  `animal_status` INT NULL,
  PRIMARY KEY (`animal_id`),
  INDEX `animal_local_idx` (`animal_local` ASC) VISIBLE,
  INDEX `animal_proprietario_idx` (`animal_proprietario` ASC) VISIBLE,
  INDEX `animal_criador_idx` (`animal_criador` ASC) VISIBLE,
  CONSTRAINT `animal_local`
    FOREIGN KEY (`animal_local`)
    REFERENCES `bd_sharas`.`pasto` (`pasto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animal_proprietario`
    FOREIGN KEY (`animal_proprietario`)
    REFERENCES `bd_sharas`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animal_criador`
    FOREIGN KEY (`animal_criador`)
    REFERENCES `bd_sharas`.`criador` (`criador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`usuario` (
  `usuario_id` INT NOT NULL,
  `usuario_nome` VARCHAR(80) NULL,
  `usuario_login` VARCHAR(45) NULL,
  `usuario_senha` VARCHAR(80) NULL,
  `usuario_email` VARCHAR(45) NULL,
  `usuario_tipo` INT(11) NULL,
  `usuario_status` INT(11) NULL,
  `usuario_notificacao` VARCHAR(120) NULL,
  `usuario_endereco` INT NULL,
  `usuario_cargo` INT(15) NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `usuario_endereco_idx` (`usuario_endereco` ASC) VISIBLE,
  CONSTRAINT `usuario_endereco`
    FOREIGN KEY (`usuario_endereco`)
    REFERENCES `bd_sharas`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`fornecedor` (
  `fornecedor_id` INT NOT NULL,
  `fornecedor_nome` VARCHAR(80) NULL,
  `fornecedor_email` VARCHAR(45) NULL,
  `fornecedor_endereco` INT(11) NULL,
  PRIMARY KEY (`fornecedor_id`),
  INDEX `fornecedor_endereco_idx` (`fornecedor_endereco` ASC) VISIBLE,
  CONSTRAINT `fornecedor_endereco`
    FOREIGN KEY (`fornecedor_endereco`)
    REFERENCES `bd_sharas`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`telefone_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`telefone_cliente` (
  `telefone_id` INT NOT NULL,
  `telefone_num` INT(15) NULL,
  `telefone_proprietario` INT(15) NULL,
  PRIMARY KEY (`telefone_id`),
  INDEX `telefone_proprietario_idx` (`telefone_proprietario` ASC) VISIBLE,
  CONSTRAINT `telefone_proprietario`
    FOREIGN KEY (`telefone_proprietario`)
    REFERENCES `bd_sharas`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`preco` (
  `preco_id` INT NOT NULL,
  `preco_valor` FLOAT NULL,
  `preco_servico` VARCHAR(45) NULL,
  PRIMARY KEY (`preco_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`servico` (
  `servico_id` INT NOT NULL,
  `servico_desc` VARCHAR(45) NULL,
  `servico_valor` INT NULL,
  `servico_usuario` INT NULL,
  `servico_cliente` INT NULL,
  `servico_inicio` DATE NULL,
  `servico_termino` DATE NULL,
  PRIMARY KEY (`servico_id`),
  INDEX `servico_usuario_idx` (`servico_usuario` ASC) VISIBLE,
  INDEX `servico_cliente_idx` (`servico_cliente` ASC) VISIBLE,
  INDEX `servico_valor_idx` (`servico_valor` ASC) VISIBLE,
  CONSTRAINT `servico_usuario`
    FOREIGN KEY (`servico_usuario`)
    REFERENCES `bd_sharas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servico_cliente`
    FOREIGN KEY (`servico_cliente`)
    REFERENCES `bd_sharas`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servico_valor`
    FOREIGN KEY (`servico_valor`)
    REFERENCES `bd_sharas`.`preco` (`preco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`celeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`celeiro` (
  `celeiro_id` INT NOT NULL,
  `celeiro_udm` VARCHAR(45) NULL,
  `celeiro_produto` VARCHAR(45) NULL,
  `celeiro_qtd` FLOAT NULL,
  `celeiro_produto_desc` VARCHAR(120) NULL,
  `celeiro_esgotado` DATE NULL,
  PRIMARY KEY (`celeiro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`log` (
  `log_id` INT NOT NULL,
  `log_acao` VARCHAR(45) NULL,
  `log_entidade` VARCHAR(45) NULL,
  `log_usuario` VARCHAR(45) NULL,
  `log_time` TIME NULL,
  `log_row` VARCHAR(45) NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`compra` (
  `compra_id` INT NOT NULL,
  `compra_produto` INT NULL,
  `compra_fornecedor` INT NULL,
  `compra_data` DATE NULL,
  `compra_valor` FLOAT NULL,
  `compra_entrega` DATE NULL,
  `compra_parc` INT(11) NULL,
  `compra_qtd` INT(11) NULL,
  `compra_udm` VARCHAR(45) NULL,
  PRIMARY KEY (`compra_id`),
  INDEX `compra_produto_idx` (`compra_produto` ASC) VISIBLE,
  INDEX `compra_fornecedor_idx` (`compra_fornecedor` ASC) VISIBLE,
  CONSTRAINT `compra_produto`
    FOREIGN KEY (`compra_produto`)
    REFERENCES `bd_sharas`.`celeiro` (`celeiro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_fornecedor`
    FOREIGN KEY (`compra_fornecedor`)
    REFERENCES `bd_sharas`.`fornecedor` (`fornecedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`telefone_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`telefone_fornecedor` (
  `telefone_id` INT NOT NULL,
  `telefone_num` INT(15) NULL,
  `telefone_proprietario` INT(15) NULL,
  PRIMARY KEY (`telefone_id`),
  INDEX `telefone_proprietario0_idx` (`telefone_proprietario` ASC) VISIBLE,
  CONSTRAINT `telefone_proprietario0`
    FOREIGN KEY (`telefone_proprietario`)
    REFERENCES `bd_sharas`.`fornecedor` (`fornecedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`telefone_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`telefone_usuario` (
  `telefone_id` INT NOT NULL,
  `telefone_num` INT(15) NULL,
  `telefone_proprietario` INT(15) NULL,
  PRIMARY KEY (`telefone_id`),
  INDEX `telefone_proprietario1_idx` (`telefone_proprietario` ASC) VISIBLE,
  CONSTRAINT `telefone_proprietario1`
    FOREIGN KEY (`telefone_proprietario`)
    REFERENCES `bd_sharas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`telefone_criador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`telefone_criador` (
  `telefone_id` INT NOT NULL,
  `telefone_num` INT(15) NULL,
  `telefone_proprietario` INT(15) NULL,
  PRIMARY KEY (`telefone_id`),
  INDEX `telefone_proprietario2_idx` (`telefone_proprietario` ASC) VISIBLE,
  CONSTRAINT `telefone_proprietario2`
    FOREIGN KEY (`telefone_proprietario`)
    REFERENCES `bd_sharas`.`criador` (`criador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`terceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`terceiros` (
  `terceiros_id` INT NOT NULL,
  `terceiros_valor` FLOAT NULL,
  `terceiros_desc` VARCHAR(80) NULL,
  `terceiros_inicio` DATE NULL,
  `terceiros_termino` DATE NULL,
  `terceiros_prestador` VARCHAR(45) NULL,
  PRIMARY KEY (`terceiros_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`consulta` (
  `consulta_id` INT NOT NULL,
  `consulta_veterinario` INT NULL,
  `consulta_valor` FLOAT NULL,
  `consulta_inicio` DATE NULL,
  `consulta_termino` DATE NULL,
  `consulta_diagnostico` VARCHAR(120) NULL,
  `consulta_tratamento` VARCHAR(120) NULL,
  `consulta_animal` INT NULL,
  PRIMARY KEY (`consulta_id`),
  INDEX `consulta_animal_idx` (`consulta_animal` ASC) VISIBLE,
  INDEX `consulta_veterinario_idx` (`consulta_veterinario` ASC) VISIBLE,
  CONSTRAINT `consulta_animal`
    FOREIGN KEY (`consulta_animal`)
    REFERENCES `bd_sharas`.`animal` (`animal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `consulta_veterinario`
    FOREIGN KEY (`consulta_veterinario`)
    REFERENCES `bd_sharas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`carteira_vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`carteira_vacina` (
  `carteira_vacina_id` INT NOT NULL,
  `carteira_vacina_nome` VARCHAR(45) NULL,
  `carteira_vacina_desc` VARCHAR(120) NULL,
  `carteira_vacina_data` DATE NULL,
  `carteira_vacina_animal` INT NULL,
  `carteira_vacina_usuario` INT NULL,
  `carteira_vacina_vacina` INT(11) NULL,
  PRIMARY KEY (`carteira_vacina_id`),
  INDEX `vacina_animal_idx` (`carteira_vacina_animal` ASC) VISIBLE,
  INDEX `carteira_vacina_usuario_idx` (`carteira_vacina_usuario` ASC) VISIBLE,
  CONSTRAINT `carteira_vacina_animal`
    FOREIGN KEY (`carteira_vacina_animal`)
    REFERENCES `bd_sharas`.`animal` (`animal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carteira_vacina_usuario`
    FOREIGN KEY (`carteira_vacina_usuario`)
    REFERENCES `bd_sharas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`rh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`rh` (
  `rg_id` INT NOT NULL,
  `rh_inicio` DATE NULL,
  `rh_termino` DATE NULL,
  `rh_usuario` INT NULL,
  `rh_salario` FLOAT NULL,
  `rh_horas_dia` INT(11) NULL,
  PRIMARY KEY (`rg_id`),
  INDEX `rh_usuario_idx` (`rh_usuario` ASC) VISIBLE,
  CONSTRAINT `rh_usuario`
    FOREIGN KEY (`rh_usuario`)
    REFERENCES `bd_sharas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`ferrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`ferrador` (
  `ferrador_id` INT NOT NULL,
  `ferrador_nome` VARCHAR(45) NULL,
  `ferrador_endereco` INT NULL,
  `ferrador_telefone` INT NULL,
  `ferrador_email` VARCHAR(45) NULL,
  `ferrador_conta` INT NULL,
  PRIMARY KEY (`ferrador_id`),
  INDEX `ferrador_endereco_idx` (`ferrador_endereco` ASC) VISIBLE,
  CONSTRAINT `ferrador_endereco`
    FOREIGN KEY (`ferrador_endereco`)
    REFERENCES `bd_sharas`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`ferrajamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`ferrajamento` (
  `ferrajamento_id` INT NOT NULL,
  `ferrajamento_ferrador` INT NULL,
  `ferrajamento_animal` INT NULL,
  `ferrajamento_valor` FLOAT NULL,
  PRIMARY KEY (`ferrajamento_id`),
  INDEX `ferrajamento_animal_idx` (`ferrajamento_animal` ASC) VISIBLE,
  INDEX `ferrajamento_ferrador_idx` (`ferrajamento_ferrador` ASC) VISIBLE,
  CONSTRAINT `ferrajamento_animal`
    FOREIGN KEY (`ferrajamento_animal`)
    REFERENCES `bd_sharas`.`animal` (`animal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ferrajamento_ferrador`
    FOREIGN KEY (`ferrajamento_ferrador`)
    REFERENCES `bd_sharas`.`ferrador` (`ferrador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`telefone_ferrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`telefone_ferrador` (
  `telefone_id` INT NOT NULL,
  `telefone_num` INT(15) NULL,
  `telefone_proprietario` INT(15) NULL,
  PRIMARY KEY (`telefone_id`),
  INDEX `telefone_proprietario20_idx` (`telefone_proprietario` ASC) VISIBLE,
  CONSTRAINT `telefone_proprietario20`
    FOREIGN KEY (`telefone_proprietario`)
    REFERENCES `bd_sharas`.`ferrador` (`ferrador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`conta_banco_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`conta_banco_usuario` (
  `conta_banco_id` INT NOT NULL,
  `conta_banco_proprietario` INT NULL,
  `conta_banco_cpf/cnpj` INT(11) NULL,
  `conta_banco_agencia` VARCHAR(45) NULL,
  `conta_banco_tipo` INT NULL,
  `conta_banco_conta` INT(11) NULL,
  `conta_banco_banco` VARCHAR(45) NULL,
  PRIMARY KEY (`conta_banco_id`),
  INDEX `conta_banco_proprietario_idx` (`conta_banco_proprietario` ASC) VISIBLE,
  CONSTRAINT `conta_banco_proprietario`
    FOREIGN KEY (`conta_banco_proprietario`)
    REFERENCES `bd_sharas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`conta_banco_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`conta_banco_fornecedor` (
  `conta_banco_id` INT NOT NULL,
  `conta_banco_proprietario` INT NULL,
  `conta_banco_cpf/cnpj` INT(11) NULL,
  `conta_banco_agencia` VARCHAR(45) NULL,
  `conta_banco_tipo` INT NULL,
  `conta_banco_conta` INT(11) NULL,
  `conta_banco_banco` VARCHAR(45) NULL,
  PRIMARY KEY (`conta_banco_id`),
  INDEX `conta_banco_proprietario0_idx` (`conta_banco_proprietario` ASC) VISIBLE,
  CONSTRAINT `conta_banco_proprietario0`
    FOREIGN KEY (`conta_banco_proprietario`)
    REFERENCES `bd_sharas`.`fornecedor` (`fornecedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`conta_banco_ferrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`conta_banco_ferrador` (
  `conta_banco_id` INT NOT NULL,
  `conta_banco_proprietario` INT NULL,
  `conta_banco_cpf/cnpj` INT(11) NULL,
  `conta_banco_agencia` VARCHAR(45) NULL,
  `conta_banco_tipo` INT NULL,
  `conta_banco_conta` INT(11) NULL,
  `conta_banco_banco` VARCHAR(45) NULL,
  PRIMARY KEY (`conta_banco_id`),
  INDEX `conta_banco_proprietario00_idx` (`conta_banco_proprietario` ASC) VISIBLE,
  CONSTRAINT `conta_banco_proprietario00`
    FOREIGN KEY (`conta_banco_proprietario`)
    REFERENCES `bd_sharas`.`ferrador` (`ferrador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`conta_banco_criador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`conta_banco_criador` (
  `conta_banco_id` INT NOT NULL,
  `conta_banco_proprietario` INT NULL,
  `conta_banco_cpf/cnpj` INT(11) NULL,
  `conta_banco_agencia` VARCHAR(45) NULL,
  `conta_banco_tipo` INT NULL,
  `conta_banco_conta` INT(11) NULL,
  `conta_banco_banco` VARCHAR(45) NULL,
  PRIMARY KEY (`conta_banco_id`),
  INDEX `conta_banco_proprietario000_idx` (`conta_banco_proprietario` ASC) VISIBLE,
  CONSTRAINT `conta_banco_proprietario000`
    FOREIGN KEY (`conta_banco_proprietario`)
    REFERENCES `bd_sharas`.`criador` (`criador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`conta_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`conta_receber` (
  `conta_receber_id` INT NOT NULL,
  `conta_receber_venc` DATE NULL,
  `conta_receber_desc` VARCHAR(120) NULL,
  `conta_receber_cliente` INT NULL,
  `conta_receber_cons` VARCHAR(45) NULL,
  PRIMARY KEY (`conta_receber_id`),
  INDEX `conta_receber_cliente_idx` (`conta_receber_cliente` ASC) VISIBLE,
  CONSTRAINT `conta_receber_cliente`
    FOREIGN KEY (`conta_receber_cliente`)
    REFERENCES `bd_sharas`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sharas`.`conta_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sharas`.`conta_pagar` (
  `conta_pagar_id` INT NOT NULL,
  `conta_pagar_venc` DATE NULL,
  `conta_pagar_desc` VARCHAR(120) NULL,
  `conta_pagar_fornecedor` INT NULL,
  `conta_pagar_terceiro` VARCHAR(45) NULL,
  PRIMARY KEY (`conta_pagar_id`),
  INDEX `conta_pagar_fornecedor_idx` (`conta_pagar_fornecedor` ASC) VISIBLE,
  CONSTRAINT `conta_pagar_fornecedor`
    FOREIGN KEY (`conta_pagar_fornecedor`)
    REFERENCES `bd_sharas`.`fornecedor` (`fornecedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
