/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FerrajamentoDAO;
import funcoes.Telas;
import model.Ferrajamento;

/**
 *
 * @author maikon.rosa
 */
public class JF_ferrageamento extends javax.swing.JFrame {

    /**
     * Creates new form JF_ferrageamento
     */
    public JF_ferrageamento() {
        initComponents();
    }
    Telas telas = new Telas();
    FerrajamentoDAO ferrajamentoDao = new FerrajamentoDAO();
    Ferrajamento ferrajamento = new Ferrajamento();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_animais = new javax.swing.JButton();
        btn_celeiro = new javax.swing.JButton();
        btn_veterinario = new javax.swing.JButton();
        btn_financeiro = new javax.swing.JButton();
        btn_pastagem = new javax.swing.JButton();
        btn_ferrajamento = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        btn_calendario = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        home = new javax.swing.JTabbedPane();
        Jferra = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_ferrajamento_ferrador = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txt_ferrajamento_animal = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txt_ferrajamento_valor = new javax.swing.JTextField();
        btn_cadastrar_ferrajamento = new javax.swing.JButton();
        btn_excluir_ferrajamento = new javax.swing.JButton();
        btn_alterar_ferrajamento = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        tab_ferrajamento = new javax.swing.JTable();
        jButton31 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        txt_ferrajamento_pesquisa = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        txt_ferrajamento_descricao = new javax.swing.JTextArea();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txt_ferrajamento_id = new javax.swing.JTextField();
        data_ferrajamento_inicio = new com.toedter.calendar.JDateChooser();
        data_ferrajamento_termino = new com.toedter.calendar.JDateChooser();
        sem_ferrador_ferrajamento = new javax.swing.JLabel();
        sem_animal_ferrajamento = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        jdata = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jnome = new javax.swing.JTextField();
        btn_animais1 = new javax.swing.JButton();
        btn_rh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_usuario1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        btn_animais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cavalo.png"))); // NOI18N
        btn_animais.setText("Animais       ");
        btn_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animaisActionPerformed(evt);
            }
        });

        btn_celeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_celeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celeiro.png"))); // NOI18N
        btn_celeiro.setText("Celeiro          ");
        btn_celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_celeiroActionPerformed(evt);
            }
        });

        btn_veterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_veterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/veterinario.png"))); // NOI18N
        btn_veterinario.setText("Consultas ");
        btn_veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veterinarioActionPerformed(evt);
            }
        });

        btn_financeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro.png"))); // NOI18N
        btn_financeiro.setText("Financeiro     ");
        btn_financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_financeiroActionPerformed(evt);
            }
        });

        btn_pastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_pastagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pastagem.png"))); // NOI18N
        btn_pastagem.setText("Pastagem  ");
        btn_pastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pastagemActionPerformed(evt);
            }
        });

        btn_ferrajamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ferrajamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ferrajamento.png"))); // NOI18N
        btn_ferrajamento.setText("Casco / Ferro");
        btn_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ferrajamentoActionPerformed(evt);
            }
        });

        btn_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_usuario.setText(" Usuários ");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        btn_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendario.png"))); // NOI18N
        btn_calendario.setText("Calendário");
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log.png"))); // NOI18N
        btn_log.setText("Log          ");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        home.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 153, 153)));

        Jferra.setBackground(new java.awt.Color(255, 255, 255));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Data de inicio:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Data de término:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Ferrador:");

        txt_ferrajamento_ferrador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Animal:");

        txt_ferrajamento_animal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Valor:");

        txt_ferrajamento_valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ferrajamento_valor.setText("0.00");

        btn_cadastrar_ferrajamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cadastrar_ferrajamento.setText("Cadastrar");
        btn_cadastrar_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_ferrajamentoActionPerformed(evt);
            }
        });

        btn_excluir_ferrajamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_excluir_ferrajamento.setText("Excluir");
        btn_excluir_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_ferrajamentoActionPerformed(evt);
            }
        });

        btn_alterar_ferrajamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_alterar_ferrajamento.setText("Alterar");
        btn_alterar_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_ferrajamentoActionPerformed(evt);
            }
        });

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tab_ferrajamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Inicio", "Término", "Ferrador", "Animal", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_ferrajamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ferrajamentoMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tab_ferrajamento);

        jButton31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton31.setText("Buscar");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Pesquisar:");

        txt_ferrajamento_pesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_ferrajamento_descricao.setColumns(20);
        txt_ferrajamento_descricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ferrajamento_descricao.setRows(5);
        jScrollPane13.setViewportView(txt_ferrajamento_descricao);

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60.setText("Descrição:");

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel61.setText("ID:");

        txt_ferrajamento_id.setEditable(false);
        txt_ferrajamento_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        sem_ferrador_ferrajamento.setForeground(new java.awt.Color(255, 0, 0));

        sem_animal_ferrajamento.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout JferraLayout = new javax.swing.GroupLayout(Jferra);
        Jferra.setLayout(JferraLayout);
        JferraLayout.setHorizontalGroup(
            JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JferraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JferraLayout.createSequentialGroup()
                        .addComponent(btn_cadastrar_ferrajamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir_ferrajamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar_ferrajamento))
                    .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sem_ferrador_ferrajamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(data_ferrajamento_termino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(data_ferrajamento_inicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ferrajamento_ferrador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ferrajamento_animal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ferrajamento_valor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(sem_animal_ferrajamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61)
                    .addComponent(txt_ferrajamento_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(txt_ferrajamento_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31))
                .addContainerGap())
        );
        JferraLayout.setVerticalGroup(
            JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JferraLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JferraLayout.createSequentialGroup()
                        .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JferraLayout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ferrajamento_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ferrajamento_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton31))
                    .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JferraLayout.createSequentialGroup()
                            .addComponent(jLabel42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(data_ferrajamento_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(jLabel43)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(data_ferrajamento_termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(jLabel44)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ferrajamento_ferrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sem_ferrador_ferrajamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel45)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ferrajamento_animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sem_animal_ferrajamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(jLabel46)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ferrajamento_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addGroup(JferraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_cadastrar_ferrajamento)
                                .addComponent(btn_excluir_ferrajamento)
                                .addComponent(btn_alterar_ferrajamento)))
                        .addComponent(jSeparator10)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        home.addTab("Ferrageamento", Jferra);

        btn_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel84.setText("Seja Bem-Vindo");

        btn_animais1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_animais1.setText("Cliente        ");
        btn_animais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animais1ActionPerformed(evt);
            }
        });

        btn_rh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_rh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manutencao.png"))); // NOI18N
        btn_rh.setText("R. H.         ");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_usuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/service.png"))); // NOI18N
        btn_usuario1.setText("Serviços");
        btn_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel84)
                        .addGap(62, 62, 62))
                    .addComponent(btn_animais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_celeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_ferrajamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pastagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_veterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_financeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_rh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_animais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btn_animais)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_animais1)
                                .addGap(5, 5, 5)
                                .addComponent(btn_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_celeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ferrajamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pastagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_veterinario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_financeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_rh))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_ferrajamentoActionPerformed
        String nome = jnome.getText();
        java.sql.Date sqldate_ferrajamento_inicio = new java.sql.Date(data_ferrajamento_inicio.getDate().getTime());
        ferrajamento.setFerrajamento_inicio(sqldate_ferrajamento_inicio);

        java.sql.Date sqldate_ferrajamento_termino = new java.sql.Date(data_ferrajamento_termino.getDate().getTime());
        ferrajamento.setFerrajamento_termino(sqldate_ferrajamento_termino);

        ferrajamento.setFerrajamento_animal(txt_ferrajamento_animal.getText());
        ferrajamento.setFerrajamento_ferrador(txt_ferrajamento_ferrador.getText());
        ferrajamento.setFerrajamento_valor(Float.parseFloat(txt_ferrajamento_valor.getText()));
        ferrajamento.setFerrajamento_descricao(txt_ferrajamento_descricao.getText());

        if (!"".equals(txt_ferrajamento_animal.getText())) {
            if (!"".equals(txt_ferrajamento_ferrador.getText())) {
                ferrajamentoDao.salvarFerrajamento(ferrajamento, nome, this);
                ferrajamentoDao.consultarFerrajamento(txt_ferrajamento_pesquisa, tab_ferrajamento, this);
                txt_ferrajamento_id.setText("");
                data_ferrajamento_inicio.setCalendar(null);
                data_ferrajamento_termino.setCalendar(null);
                txt_ferrajamento_ferrador.setText("");
                txt_ferrajamento_animal.setText("0.00");
                txt_ferrajamento_valor.setText("");
                txt_ferrajamento_descricao.setText("");
                sem_ferrador_ferrajamento.setText("");
                sem_animal_ferrajamento.setText("");
            } else {
                sem_ferrador_ferrajamento.setText("Campo obrigatório");
            }

        } else {
            sem_animal_ferrajamento.setText("Campo obrigatório");
        }
    }//GEN-LAST:event_btn_cadastrar_ferrajamentoActionPerformed

    private void btn_excluir_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_ferrajamentoActionPerformed
        String how = txt_ferrajamento_id.getText();
        String nome = jnome.getText();
        ferrajamento.setFerrajamento_id(Integer.valueOf(txt_ferrajamento_id.getText()));
        ferrajamentoDao.apagarFerrajamento(ferrajamento, nome, how, this);
        data_ferrajamento_inicio.setCalendar(null);
        data_ferrajamento_termino.setCalendar(null);
        txt_ferrajamento_ferrador.setText("");
        txt_ferrajamento_animal.setText("");
        txt_ferrajamento_valor.setText("0.00");
        txt_ferrajamento_id.setText("");
        txt_ferrajamento_descricao.setText("");
        ferrajamentoDao.consultarFerrajamento(txt_ferrajamento_pesquisa, tab_ferrajamento, this);
    }//GEN-LAST:event_btn_excluir_ferrajamentoActionPerformed

    private void btn_alterar_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_ferrajamentoActionPerformed
        String how = txt_ferrajamento_id.getText();
        String nome = jnome.getText();
        ferrajamento.setFerrajamento_id(Integer.parseInt(txt_ferrajamento_id.getText()));
        java.sql.Date sqldate_ferrajamento_inicio = new java.sql.Date(data_ferrajamento_inicio.getDate().getTime());
        ferrajamento.setFerrajamento_inicio(sqldate_ferrajamento_inicio);

        java.sql.Date sqldate_ferrajamento_termino = new java.sql.Date(data_ferrajamento_termino.getDate().getTime());
        ferrajamento.setFerrajamento_termino(sqldate_ferrajamento_termino);
        ferrajamento.setFerrajamento_animal(txt_ferrajamento_animal.getText());
        ferrajamento.setFerrajamento_ferrador(txt_ferrajamento_ferrador.getText());
        ferrajamento.setFerrajamento_valor(Float.parseFloat(txt_ferrajamento_valor.getText()));
        ferrajamento.setFerrajamento_descricao(txt_ferrajamento_descricao.getText());
        ferrajamentoDao.alterarFerrajamento(ferrajamento, nome, how, this);
        ferrajamentoDao.consultarFerrajamento(txt_ferrajamento_pesquisa, tab_ferrajamento, this);
    }//GEN-LAST:event_btn_alterar_ferrajamentoActionPerformed

    private void tab_ferrajamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ferrajamentoMouseClicked
        int linha = tab_ferrajamento.getSelectedRow();
        String valor = String.valueOf(tab_ferrajamento.getValueAt(linha, 0));
        int ferrajamentoID = Integer.valueOf(valor);
        ferrajamentoDao.consultarFerrajamentoID(ferrajamentoID, txt_ferrajamento_id, data_ferrajamento_inicio, data_ferrajamento_termino, txt_ferrajamento_ferrador, txt_ferrajamento_animal, txt_ferrajamento_valor, txt_ferrajamento_descricao, this);
        btn_cadastrar_ferrajamento.setEnabled(false);
        btn_excluir_ferrajamento.setEnabled(true);
        btn_alterar_ferrajamento.setEnabled(true);
        sem_ferrador_ferrajamento.setText("");
        sem_animal_ferrajamento.setText("");
    }//GEN-LAST:event_tab_ferrajamentoMouseClicked

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        ferrajamentoDao.consultarFerrajamento(txt_ferrajamento_pesquisa, tab_ferrajamento, this);
        txt_ferrajamento_id.setText("");
        data_ferrajamento_inicio.setCalendar(null);
        data_ferrajamento_termino.setCalendar(null);
        txt_ferrajamento_ferrador.setText("");
        txt_ferrajamento_animal.setText("");
        txt_ferrajamento_valor.setText("0.00");
        txt_ferrajamento_descricao.setText("");
        btn_cadastrar_ferrajamento.setEnabled(true);
        btn_excluir_ferrajamento.setEnabled(false);
        btn_alterar_ferrajamento.setEnabled(false);
        sem_ferrador_ferrajamento.setText("");
        sem_animal_ferrajamento.setText("");
    }//GEN-LAST:event_jButton31ActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        telas.alterar(this,1);
    }                                        
    private void btn_animais1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
         telas.alterar(this, 2);
    }   
    
    private void btn_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        telas.alterar(this, 3);        
    }    
    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {                                               
       telas.alterar(this, 4);
    }         
    private void btn_animaisActionPerformed(java.awt.event.ActionEvent evt) {                                            
       telas.alterar(this, 5);
    }                  
 private void btn_pastagemActionPerformed(java.awt.event.ActionEvent evt) {                                             
      telas.alterar(this, 6);
    }                                            
    private void btn_celeiroActionPerformed(java.awt.event.ActionEvent evt) {                                            
      telas.alterar(this, 7);
    }                                           
   private void btn_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       telas.alterar(this, 8);
    }                                                
private void btn_veterinarioActionPerformed(java.awt.event.ActionEvent evt) {                                                
     telas.alterar(this, 9);
    }                                               

    private void btn_financeiroActionPerformed(java.awt.event.ActionEvent evt) {                                               
        telas.alterar(this, 10);
    }    
       private void btn_rhActionPerformed(java.awt.event.ActionEvent evt) {                                       
       telas.alterar(this, 11);
        
    }        
  private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
    telas.alterar(this, 12);
    }                                           
    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {                                        
 telas.alterar(this, 13);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_ferrageamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_ferrageamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_ferrageamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_ferrageamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_ferrageamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jferra;
    private javax.swing.JButton btn_alterar_ferrajamento;
    private javax.swing.JButton btn_animais;
    private javax.swing.JButton btn_animais1;
    private javax.swing.JButton btn_cadastrar_ferrajamento;
    private javax.swing.JButton btn_calendario;
    private javax.swing.JButton btn_celeiro;
    private javax.swing.JButton btn_excluir_ferrajamento;
    private javax.swing.JButton btn_ferrajamento;
    private javax.swing.JButton btn_financeiro;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_pastagem;
    private javax.swing.JButton btn_rh;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton btn_usuario1;
    private javax.swing.JButton btn_veterinario;
    private com.toedter.calendar.JDateChooser data_ferrajamento_inicio;
    private com.toedter.calendar.JDateChooser data_ferrajamento_termino;
    private javax.swing.JTabbedPane home;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JLabel jdata;
    private javax.swing.JTextField jnome;
    private javax.swing.JLabel sem_animal_ferrajamento;
    private javax.swing.JLabel sem_ferrador_ferrajamento;
    private javax.swing.JTable tab_ferrajamento;
    private javax.swing.JTextField txt_ferrajamento_animal;
    private javax.swing.JTextArea txt_ferrajamento_descricao;
    private javax.swing.JTextField txt_ferrajamento_ferrador;
    private javax.swing.JTextField txt_ferrajamento_id;
    private javax.swing.JTextField txt_ferrajamento_pesquisa;
    private javax.swing.JTextField txt_ferrajamento_valor;
    // End of variables declaration//GEN-END:variables
}
