/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PastagemDAO;
import model.Pastagem;

/**
 *
 * @author maikon.rosa
 */
public class JF_Pastagem extends javax.swing.JFrame {

    /**
     * Creates new form JF_Pastagem
     */
    public JF_Pastagem() {
        initComponents();
    }
    PastagemDAO pastagemDao = new PastagemDAO();
    Pastagem pastagem = new Pastagem();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_animais = new javax.swing.JButton();
        btn_celeiro = new javax.swing.JButton();
        btn_veterinario = new javax.swing.JButton();
        btn_financeiro = new javax.swing.JButton();
        btn_pastagem = new javax.swing.JButton();
        btn_ferrajamento = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        btn_calendario = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        home = new javax.swing.JTabbedPane();
        Jpastagem = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtpastagemid = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtpastagemanotacao = new javax.swing.JTextArea();
        btncadastrarpastagem = new javax.swing.JButton();
        btn_excluir_pastagem = new javax.swing.JButton();
        btn_alterar_pastagem = new javax.swing.JButton();
        cbpastagemnumero = new javax.swing.JComboBox<>();
        cbpastagemqualidade = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane12 = new javax.swing.JScrollPane();
        tabpastagem = new javax.swing.JTable();
        jLabel58 = new javax.swing.JLabel();
        txtpesquisapastagem = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jdate_pastagem_data = new com.toedter.calendar.JDateChooser();
        txtpastagemquantidade = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        sem_numero_pasto = new javax.swing.JLabel();
        sem_qualidade_pastagem = new javax.swing.JLabel();
        sem_quantidade_pasto = new javax.swing.JLabel();
        sem_numero_pasto2 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        jdata = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jnome = new javax.swing.JTextField();
        btn_animais1 = new javax.swing.JButton();
        btn_rh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_usuario1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        atalho_animais = new javax.swing.JMenuItem();
        atalho_treinamento = new javax.swing.JMenuItem();
        atalho_consulta = new javax.swing.JMenuItem();
        atalho_finaceiro = new javax.swing.JMenuItem();
        atalho_rh = new javax.swing.JMenuItem();
        atalho_ferrajamento = new javax.swing.JMenuItem();
        atalho_log = new javax.swing.JMenuItem();
        atalho_pastagem = new javax.swing.JMenuItem();
        atalho_usuario = new javax.swing.JMenuItem();
        atalho_calendario = new javax.swing.JMenuItem();
        atalho_celeiro = new javax.swing.JMenu();
        atalho_feno = new javax.swing.JMenuItem();
        atalho_racao = new javax.swing.JMenuItem();
        atalho_serragem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        btn_animais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cavalo.png"))); // NOI18N
        btn_animais.setText("Animais       ");
        btn_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animaisActionPerformed(evt);
            }
        });

        btn_celeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_celeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celeiro.png"))); // NOI18N
        btn_celeiro.setText("Celeiro          ");
        btn_celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_celeiroActionPerformed(evt);
            }
        });

        btn_veterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_veterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/veterinario.png"))); // NOI18N
        btn_veterinario.setText("Consultas ");
        btn_veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veterinarioActionPerformed(evt);
            }
        });

        btn_financeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro.png"))); // NOI18N
        btn_financeiro.setText("Financeiro     ");
        btn_financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_financeiroActionPerformed(evt);
            }
        });

        btn_pastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_pastagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pastagem.png"))); // NOI18N
        btn_pastagem.setText("Pastagem  ");
        btn_pastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pastagemActionPerformed(evt);
            }
        });

        btn_ferrajamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ferrajamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ferrajamento.png"))); // NOI18N
        btn_ferrajamento.setText("Casco / Ferro");
        btn_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ferrajamentoActionPerformed(evt);
            }
        });

        btn_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_usuario.setText(" Usuários ");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        btn_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendario.png"))); // NOI18N
        btn_calendario.setText("Calendário");
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log.png"))); // NOI18N
        btn_log.setText("Log          ");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        home.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 153, 153)));
        home.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homeComponentShown(evt);
            }
        });

        Jpastagem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/g4116.png"))); // NOI18N

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("ID:");

        txtpastagemid.setEditable(false);
        txtpastagemid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("Número:");

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Qualidade:");

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText("Anotações:");

        txtpastagemanotacao.setColumns(20);
        txtpastagemanotacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpastagemanotacao.setRows(5);
        jScrollPane11.setViewportView(txtpastagemanotacao);

        btncadastrarpastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncadastrarpastagem.setText("Cadastrar");
        btncadastrarpastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarpastagemActionPerformed(evt);
            }
        });

        btn_excluir_pastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_excluir_pastagem.setText("Excluir");
        btn_excluir_pastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_pastagemActionPerformed(evt);
            }
        });

        btn_alterar_pastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_alterar_pastagem.setText("Alterar");
        btn_alterar_pastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_pastagemActionPerformed(evt);
            }
        });

        cbpastagemnumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbpastagemnumero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número do Pasto", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cbpastagemnumero.setToolTipText("");
        cbpastagemnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpastagemnumeroActionPerformed(evt);
            }
        });

        cbpastagemqualidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbpastagemqualidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Ruim", "Regular", "Bom", "Muito Bom" }));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tabpastagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NUMERO", "QUANTIDADE", "QUALIDADE"
            }
        ));
        tabpastagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabpastagemMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tabpastagem);

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setText("Pesquisar:");

        txtpesquisapastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisapastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisapastagemActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton19.setText("Buscar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel62.setText("Data:");

        txtpastagemquantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpastagemquantidade.setText("0");

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Quantidade de animais:");

        sem_numero_pasto.setForeground(new java.awt.Color(255, 0, 0));

        sem_qualidade_pastagem.setForeground(new java.awt.Color(255, 0, 0));

        sem_quantidade_pasto.setForeground(new java.awt.Color(255, 0, 0));

        sem_numero_pasto2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout JpastagemLayout = new javax.swing.GroupLayout(Jpastagem);
        Jpastagem.setLayout(JpastagemLayout);
        JpastagemLayout.setHorizontalGroup(
            JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpastagemLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel51)
                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpastagemLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56)
                            .addComponent(jLabel52)
                            .addComponent(txtpastagemid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54)
                            .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtpastagemquantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpastagemLayout.createSequentialGroup()
                                    .addComponent(jLabel55)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbpastagemqualidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpastagemLayout.createSequentialGroup()
                                    .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(JpastagemLayout.createSequentialGroup()
                                            .addComponent(jLabel62)
                                            .addGap(19, 19, 19)))
                                    .addGap(10, 10, 10)
                                    .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jdate_pastagem_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbpastagemnumero, 0, 1, Short.MAX_VALUE)))
                                .addComponent(sem_numero_pasto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sem_qualidade_pastagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sem_quantidade_pasto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpastagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpastagemLayout.createSequentialGroup()
                                .addComponent(btncadastrarpastagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir_pastagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_alterar_pastagem)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpastagemLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpastagemLayout.createSequentialGroup()
                        .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpastagemLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel58))
                            .addGroup(JpastagemLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton19)
                                    .addComponent(txtpesquisapastagem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpastagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpastagemLayout.createSequentialGroup()
                    .addGap(513, 513, 513)
                    .addComponent(sem_numero_pasto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(412, 412, 412)))
        );
        JpastagemLayout.setVerticalGroup(
            JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpastagemLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11)
                    .addGroup(JpastagemLayout.createSequentialGroup()
                        .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpastagemLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JpastagemLayout.createSequentialGroup()
                                        .addComponent(txtpastagemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel62))
                                    .addComponent(jdate_pastagem_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbpastagemnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sem_numero_pasto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel55)
                                    .addComponent(cbpastagemqualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sem_qualidade_pastagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpastagemquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sem_quantidade_pasto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_alterar_pastagem)
                                    .addComponent(btn_excluir_pastagem)
                                    .addComponent(btncadastrarpastagem)))
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JpastagemLayout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpesquisapastagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton19)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpastagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpastagemLayout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(sem_numero_pasto2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        home.addTab("Pastagem", Jpastagem);

        btn_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel84.setText("Seja Bem-Vindo");

        btn_animais1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_animais1.setText("Cliente        ");
        btn_animais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animais1ActionPerformed(evt);
            }
        });

        btn_rh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_rh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manutencao.png"))); // NOI18N
        btn_rh.setText("R. H.         ");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_usuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/service.png"))); // NOI18N
        btn_usuario1.setText("Serviços");
        btn_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel84)
                        .addGap(62, 62, 62))
                    .addComponent(btn_animais1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_celeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_ferrajamento, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_pastagem, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_veterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_financeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_rh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_animais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btn_animais)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_animais1)
                                .addGap(5, 5, 5)
                                .addComponent(btn_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_celeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ferrajamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pastagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_veterinario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_financeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_rh))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Atalho ");

        atalho_animais.setText("Animais ");
        atalho_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_animaisbtn_animaisActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_animais);

        atalho_treinamento.setText("Treinamento ");
        atalho_treinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_treinamentobtn_treinamentoActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_treinamento);

        atalho_consulta.setText("Consulta ");
        atalho_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_consultabtn_veterinarioActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_consulta);

        atalho_finaceiro.setText("Financeiro ");
        atalho_finaceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_finaceirobtn_financeiroActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_finaceiro);

        atalho_rh.setText("RH");
        atalho_rh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_rhbtn_rhActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_rh);

        atalho_ferrajamento.setText("Ferrajamento");
        atalho_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_ferrajamentobtn_ferrajamentoActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_ferrajamento);

        atalho_log.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        atalho_log.setText("Historioco de ação ");
        atalho_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_logbtn_logActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_log);

        atalho_pastagem.setText("Pastagem ");
        atalho_pastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_pastagembtn_pastagemActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_pastagem);

        atalho_usuario.setText("Cadastro de usuário");
        atalho_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_usuariobtn_usuarioActionPerformed(evt);
            }
        });
        jMenu2.add(atalho_usuario);

        atalho_calendario.setText("Calendário");
        jMenu2.add(atalho_calendario);

        atalho_celeiro.setText("Celeiro ");
        atalho_celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_celeirobtn_celeiroActionPerformed(evt);
            }
        });

        atalho_feno.setText("Feno");
        atalho_feno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalho_fenoActionPerformed(evt);
            }
        });
        atalho_celeiro.add(atalho_feno);

        atalho_racao.setText("Ração ");
        atalho_celeiro.add(atalho_racao);

        atalho_serragem.setText("Serragem ");
        atalho_celeiro.add(atalho_serragem);

        jMenu2.add(atalho_celeiro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_animaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animaisActionPerformed

    }//GEN-LAST:event_btn_animaisActionPerformed

    private void btn_celeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_celeiroActionPerformed

    }//GEN-LAST:event_btn_celeiroActionPerformed

    private void btn_veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veterinarioActionPerformed

    }//GEN-LAST:event_btn_veterinarioActionPerformed

    private void btn_financeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_financeiroActionPerformed

    }//GEN-LAST:event_btn_financeiroActionPerformed

    private void btn_pastagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pastagemActionPerformed

    }//GEN-LAST:event_btn_pastagemActionPerformed

    private void btn_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ferrajamentoActionPerformed

    }//GEN-LAST:event_btn_ferrajamentoActionPerformed

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed

    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calendarioActionPerformed
        JF_calendario calendario= new JF_calendario();
        calendario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_calendarioActionPerformed

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed

    }//GEN-LAST:event_btn_logActionPerformed

    private void btncadastrarpastagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarpastagemActionPerformed
        String nome = jnome.getText();
        pastagem.setPastagem_numero(cbpastagemnumero.getSelectedIndex());
        pastagem.setPastagem_quantidade(Integer.valueOf(txtpastagemquantidade.getText()));
        pastagem.setPastegem_qualidade(cbpastagemqualidade.getSelectedIndex());
        pastagem.setPastagem_anotacao(txtpastagemanotacao.getText());

        java.sql.Date sqldate_pastagem = new java.sql.Date(jdate_pastagem_data.getDate().getTime());
        pastagem.setPastagem_data(sqldate_pastagem);

        if (!"".equals(txtpastagemquantidade.getText())) {
            if (cbpastagemqualidade.getSelectedIndex() != 0) {
                if (cbpastagemnumero.getSelectedIndex() != 0) {
                    pastagemDao.salvarPastagem(pastagem, nome, this);
                    txtpastagemquantidade.setText("");
                    txtpastagemanotacao.setText("");
                    jdate_pastagem_data.setCalendar(null);
                    sem_numero_pasto.setText("");
                    pastagemDao.consultarPastagem(txtpesquisapastagem, tabpastagem, this);
                    sem_quantidade_pasto.setText("");
                    sem_qualidade_pastagem.setText("");
                    sem_numero_pasto.setText("");
                } else {
                    sem_numero_pasto.setText("Campo obrigatório");
                }

            } else {
                sem_qualidade_pastagem.setText("Campo obrigatório");
            }
        } else {
            sem_quantidade_pasto.setText("Campo obrigatório");
        }
    }//GEN-LAST:event_btncadastrarpastagemActionPerformed

    private void btn_excluir_pastagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_pastagemActionPerformed
        String nome = jnome.getText();
        String how = txtpastagemid.getText();
        pastagem.setPastagem_id(Integer.valueOf(txtpastagemid.getText()));
        pastagemDao.apagarPastagem(pastagem, nome, how, this);
        txtpastagemid.setText("");
        jdate_pastagem_data.setCalendar(null);
        cbpastagemnumero.setSelectedIndex(1);
        txtpastagemquantidade.setText("");
        cbpastagemqualidade.setSelectedIndex(1);
        txtpastagemanotacao.setText("");
        pastagemDao.consultarPastagem(txtpesquisapastagem, tabpastagem, this);
    }//GEN-LAST:event_btn_excluir_pastagemActionPerformed

    private void btn_alterar_pastagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_pastagemActionPerformed
        String nome = jnome.getText();
        String how = txtpastagemid.getText();
        pastagem.setPastagem_id(Integer.parseInt(txtpastagemid.getText()));
        pastagem.setPastagem_numero(cbpastagemnumero.getSelectedIndex());
        pastagem.setPastagem_quantidade(Integer.parseInt(txtpastagemquantidade.getText()));
        pastagem.setPastegem_qualidade(cbpastagemqualidade.getSelectedIndex());
        pastagem.setPastagem_anotacao(txtpastagemanotacao.getText());
        java.sql.Date date_pastagem = new java.sql.Date(jdate_pastagem_data.getDate().getTime());
        pastagem.setPastagem_data(date_pastagem);
        pastagemDao.alterarPastagem(pastagem, nome, how, this);
        pastagemDao.consultarPastagem(txtpesquisapastagem, tabpastagem, this);
    }//GEN-LAST:event_btn_alterar_pastagemActionPerformed

    private void cbpastagemnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpastagemnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpastagemnumeroActionPerformed

    private void tabpastagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabpastagemMouseClicked
        int linha = tabpastagem.getSelectedRow();
        String valor = String.valueOf(tabpastagem.getValueAt(linha, 0));
        int pastagemID = Integer.valueOf(valor);
        pastagemDao.consultarPastagemID(pastagemID, txtpastagemid, txtpastagemquantidade, cbpastagemnumero, cbpastagemqualidade, txtpastagemanotacao, jdate_pastagem_data, this);
        btncadastrarpastagem.setEnabled(false);
        btn_excluir_pastagem.setEnabled(true);
        btn_alterar_pastagem.setEnabled(true);
    }//GEN-LAST:event_tabpastagemMouseClicked

    private void txtpesquisapastagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisapastagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisapastagemActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        pastagemDao.consultarPastagem(txtpesquisapastagem, tabpastagem, this);
        btncadastrarpastagem.setEnabled(true);
        txtpastagemid.setText("");
        cbpastagemnumero.setSelectedIndex(0);
        txtpastagemquantidade.setText("");
        cbpastagemqualidade.setSelectedIndex(0);
        txtpastagemanotacao.setText("");
        jdate_pastagem_data.setCalendar(null);
        btncadastrarpastagem.setEnabled(true);
        btn_excluir_pastagem.setEnabled(false);
        btn_alterar_pastagem.setEnabled(false);
        sem_quantidade_pasto.setText("");
        sem_qualidade_pastagem.setText("");
        sem_numero_pasto.setText("");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void homeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homeComponentShown

        // TODO add your handling code here:
    }//GEN-LAST:event_homeComponentShown

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed

    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_animais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_animais1ActionPerformed

    private void btn_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario1ActionPerformed
        JF_Servico s = new JF_Servico();
        s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuario1ActionPerformed

    private void atalho_animaisbtn_animaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_animaisbtn_animaisActionPerformed

    }//GEN-LAST:event_atalho_animaisbtn_animaisActionPerformed

    private void atalho_treinamentobtn_treinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_treinamentobtn_treinamentoActionPerformed

    }//GEN-LAST:event_atalho_treinamentobtn_treinamentoActionPerformed

    private void atalho_consultabtn_veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_consultabtn_veterinarioActionPerformed

    }//GEN-LAST:event_atalho_consultabtn_veterinarioActionPerformed

    private void atalho_finaceirobtn_financeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_finaceirobtn_financeiroActionPerformed

    }//GEN-LAST:event_atalho_finaceirobtn_financeiroActionPerformed

    private void atalho_rhbtn_rhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_rhbtn_rhActionPerformed

    }//GEN-LAST:event_atalho_rhbtn_rhActionPerformed

    private void atalho_ferrajamentobtn_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_ferrajamentobtn_ferrajamentoActionPerformed

    }//GEN-LAST:event_atalho_ferrajamentobtn_ferrajamentoActionPerformed

    private void atalho_logbtn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_logbtn_logActionPerformed

    }//GEN-LAST:event_atalho_logbtn_logActionPerformed

    private void atalho_pastagembtn_pastagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_pastagembtn_pastagemActionPerformed

    }//GEN-LAST:event_atalho_pastagembtn_pastagemActionPerformed

    private void atalho_usuariobtn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_usuariobtn_usuarioActionPerformed

    }//GEN-LAST:event_atalho_usuariobtn_usuarioActionPerformed

    private void atalho_fenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_fenoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_atalho_fenoActionPerformed

    private void atalho_celeirobtn_celeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalho_celeirobtn_celeiroActionPerformed

    }//GEN-LAST:event_atalho_celeirobtn_celeiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Pastagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Pastagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Pastagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Pastagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Pastagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpastagem;
    private javax.swing.JMenuItem atalho_animais;
    private javax.swing.JMenuItem atalho_calendario;
    private javax.swing.JMenu atalho_celeiro;
    private javax.swing.JMenuItem atalho_consulta;
    private javax.swing.JMenuItem atalho_feno;
    private javax.swing.JMenuItem atalho_ferrajamento;
    private javax.swing.JMenuItem atalho_finaceiro;
    private javax.swing.JMenuItem atalho_log;
    private javax.swing.JMenuItem atalho_pastagem;
    private javax.swing.JMenuItem atalho_racao;
    private javax.swing.JMenuItem atalho_rh;
    private javax.swing.JMenuItem atalho_serragem;
    private javax.swing.JMenuItem atalho_treinamento;
    private javax.swing.JMenuItem atalho_usuario;
    private javax.swing.JButton btn_alterar_pastagem;
    private javax.swing.JButton btn_animais;
    private javax.swing.JButton btn_animais1;
    private javax.swing.JButton btn_calendario;
    private javax.swing.JButton btn_celeiro;
    private javax.swing.JButton btn_excluir_pastagem;
    private javax.swing.JButton btn_ferrajamento;
    private javax.swing.JButton btn_financeiro;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_pastagem;
    private javax.swing.JButton btn_rh;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton btn_usuario1;
    private javax.swing.JButton btn_veterinario;
    private javax.swing.JButton btncadastrarpastagem;
    private javax.swing.JComboBox<String> cbpastagemnumero;
    private javax.swing.JComboBox<String> cbpastagemqualidade;
    private javax.swing.JTabbedPane home;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JLabel jdata;
    private com.toedter.calendar.JDateChooser jdate_pastagem_data;
    private javax.swing.JTextField jnome;
    private javax.swing.JLabel sem_numero_pasto;
    private javax.swing.JLabel sem_numero_pasto2;
    private javax.swing.JLabel sem_qualidade_pastagem;
    private javax.swing.JLabel sem_quantidade_pasto;
    private javax.swing.JTable tabpastagem;
    private javax.swing.JTextArea txtpastagemanotacao;
    private javax.swing.JTextField txtpastagemid;
    private javax.swing.JTextField txtpastagemquantidade;
    private javax.swing.JTextField txtpesquisapastagem;
    // End of variables declaration//GEN-END:variables
}
