/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.VeterinarioDAO;
import controller.Telas;
import model.Veterinario;

/**
 *
 * @author maikon.rosa
 */
public class JF_Veterinario extends javax.swing.JFrame {

    /**
     * Creates new form JF_Veterinario
     */
    public JF_Veterinario() {
        initComponents();
    }
    Telas telas = new Telas();
    VeterinarioDAO veterinarioDao = new VeterinarioDAO();
    Veterinario veterinario = new Veterinario();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_animais = new javax.swing.JButton();
        btn_celeiro = new javax.swing.JButton();
        btn_veterinario = new javax.swing.JButton();
        btn_financeiro = new javax.swing.JButton();
        btn_pastagem = new javax.swing.JButton();
        btn_ferrajamento = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        btn_calendario = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        home = new javax.swing.JTabbedPane();
        Jveterinario = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_veterinario_animal = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_veterinario_nome = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_veterinario_tratamento = new javax.swing.JTextArea();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_veterinario_diagnostico = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        tab_veterinario = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        txt_veterinario_pesquisa = new javax.swing.JTextField();
        btn_buscar2 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        txt_veterinario_valor = new javax.swing.JTextField();
        jdate_veterinario_inicio = new com.toedter.calendar.JDateChooser();
        jdate_veterinario_termino = new com.toedter.calendar.JDateChooser();
        btn_veterinario_cadastrar = new javax.swing.JButton();
        btn_veterinario_excluir = new javax.swing.JButton();
        btn_veterinario_alterar = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        txt_veterinario_id = new javax.swing.JTextField();
        sem_animal_veterinario = new javax.swing.JLabel();
        sem_veterinario_veterinario = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        jdata = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jnome = new javax.swing.JTextField();
        btn_animais1 = new javax.swing.JButton();
        btn_rh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_usuario1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        btn_animais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cavalo.png"))); // NOI18N
        btn_animais.setText("Animais       ");

        btn_celeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_celeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celeiro.png"))); // NOI18N
        btn_celeiro.setText("Celeiro          ");
        btn_celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_celeiroActionPerformed(evt);
            }
        });

        btn_veterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_veterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/veterinario.png"))); // NOI18N
        btn_veterinario.setText("Consultas ");
        btn_veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veterinarioActionPerformed(evt);
            }
        });

        btn_financeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro.png"))); // NOI18N
        btn_financeiro.setText("Financeiro     ");
        btn_financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_financeiroActionPerformed(evt);
            }
        });

        btn_pastagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_pastagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pastagem.png"))); // NOI18N
        btn_pastagem.setText("Pastagem  ");
        btn_pastagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pastagemActionPerformed(evt);
            }
        });

        btn_ferrajamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ferrajamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ferrajamento.png"))); // NOI18N
        btn_ferrajamento.setText("Casco / Ferro");
        btn_ferrajamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ferrajamentoActionPerformed(evt);
            }
        });

        btn_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_usuario.setText(" Usuários ");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        btn_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendario.png"))); // NOI18N
        btn_calendario.setText("Calendário");
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log.png"))); // NOI18N
        btn_log.setText("Log          ");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        home.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 153, 153)));
        home.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homeComponentShown(evt);
            }
        });

        Jveterinario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Animal:");

        txt_veterinario_animal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Veterinário responsável:");

        txt_veterinario_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_veterinario_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_veterinario_nomeActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Data do inicio do tratamento:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Data do termino do tratamento:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Diagnóstico do veterinário:");

        txt_veterinario_tratamento.setColumns(20);
        txt_veterinario_tratamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_veterinario_tratamento.setRows(5);
        jScrollPane5.setViewportView(txt_veterinario_tratamento);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Tratamento :");

        txt_veterinario_diagnostico.setColumns(20);
        txt_veterinario_diagnostico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_veterinario_diagnostico.setRows(5);
        jScrollPane6.setViewportView(txt_veterinario_diagnostico);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tab_veterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab_veterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Veterinário", "Animal", "Data inicio", "Data término"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_veterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_veterinarioMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tab_veterinario);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Pesquisar: ");

        txt_veterinario_pesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_buscar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_buscar2.setText("Buscar");
        btn_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar2ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Valor total da despesa:");

        txt_veterinario_valor.setText("0.00");
        txt_veterinario_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_veterinario_valorActionPerformed(evt);
            }
        });

        btn_veterinario_cadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_veterinario_cadastrar.setText("Cadastrar");
        btn_veterinario_cadastrar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btn_veterinario_cadastrarAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btn_veterinario_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veterinario_cadastrarActionPerformed(evt);
            }
        });

        btn_veterinario_excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_veterinario_excluir.setText("Excluir");
        btn_veterinario_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veterinario_excluirActionPerformed(evt);
            }
        });

        btn_veterinario_alterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_veterinario_alterar.setText("Alterar");
        btn_veterinario_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veterinario_alterarActionPerformed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel70.setText("ID:");
        jLabel70.setEnabled(false);

        txt_veterinario_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_veterinario_id.setEnabled(false);

        sem_animal_veterinario.setForeground(new java.awt.Color(255, 0, 0));

        sem_veterinario_veterinario.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout JveterinarioLayout = new javax.swing.GroupLayout(Jveterinario);
        Jveterinario.setLayout(JveterinarioLayout);
        JveterinarioLayout.setHorizontalGroup(
            JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JveterinarioLayout.createSequentialGroup()
                .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JveterinarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_veterinario_cadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_veterinario_excluir)
                        .addGap(18, 18, 18)
                        .addComponent(btn_veterinario_alterar)
                        .addGap(122, 122, 122))
                    .addGroup(JveterinarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel38)
                                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35)
                                .addComponent(jLabel34)
                                .addComponent(txt_veterinario_animal)
                                .addComponent(txt_veterinario_nome)
                                .addComponent(jLabel36)
                                .addComponent(jdate_veterinario_termino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdate_veterinario_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sem_animal_veterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sem_veterinario_veterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)))
                .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel70)
                    .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_veterinario_id, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_veterinario_valor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JveterinarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(txt_veterinario_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar2))
                        .addContainerGap(174, Short.MAX_VALUE))
                    .addGroup(JveterinarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JveterinarioLayout.createSequentialGroup()
                    .addGap(365, 365, 365)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(767, Short.MAX_VALUE)))
        );
        JveterinarioLayout.setVerticalGroup(
            JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JveterinarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JveterinarioLayout.createSequentialGroup()
                        .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JveterinarioLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JveterinarioLayout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_veterinario_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel70)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_veterinario_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(JveterinarioLayout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_veterinario_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscar2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JveterinarioLayout.createSequentialGroup()
                        .addComponent(txt_veterinario_animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sem_animal_veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_veterinario_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(sem_veterinario_veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_veterinario_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_veterinario_termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_veterinario_cadastrar)
                            .addComponent(btn_veterinario_excluir)
                            .addComponent(btn_veterinario_alterar))
                        .addGap(41, 41, 41))))
            .addGroup(JveterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JveterinarioLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        home.addTab("Veterinário", Jveterinario);

        btn_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel84.setText("Seja Bem-Vindo");

        btn_animais1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_animais1.setText("Cliente        ");
        btn_animais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animais1ActionPerformed(evt);
            }
        });

        btn_rh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_rh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manutencao.png"))); // NOI18N
        btn_rh.setText("R. H.         ");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_usuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/service.png"))); // NOI18N
        btn_usuario1.setText("Serviços");
        btn_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel84)
                        .addGap(62, 62, 62))
                    .addComponent(btn_animais1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_celeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_ferrajamento, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_pastagem, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_veterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_financeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_rh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_animais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btn_animais)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_animais1)
                                .addGap(5, 5, 5)
                                .addComponent(btn_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_celeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ferrajamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pastagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_veterinario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_financeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_rh))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
                             


    
   
 
  
    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        telas.alterar(this,1);
    }                                        
    private void btn_animais1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
         telas.alterar(this, 2);
    }   
    
    private void btn_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        telas.alterar(this, 3);        
    }    
    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {                                               
       telas.alterar(this, 4);
    }         
    private void btn_animaisActionPerformed(java.awt.event.ActionEvent evt) {                                            
       telas.alterar(this, 5);
    }                  
 private void btn_pastagemActionPerformed(java.awt.event.ActionEvent evt) {                                             
      telas.alterar(this, 6);
    }                                            
    private void btn_celeiroActionPerformed(java.awt.event.ActionEvent evt) {                                            
      telas.alterar(this, 7);
    }                                           
   private void btn_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       telas.alterar(this, 8);
    }                                                
private void btn_veterinarioActionPerformed(java.awt.event.ActionEvent evt) {                                                
     telas.alterar(this, 9);
    }                                               

    private void btn_financeiroActionPerformed(java.awt.event.ActionEvent evt) {                                               
        telas.alterar(this, 10);
    }    
       private void btn_rhActionPerformed(java.awt.event.ActionEvent evt) {                                       
       telas.alterar(this, 11);
        
    }        
  private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
    telas.alterar(this, 12);
    }                                           
    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {                                        
 telas.alterar(this, 13);
    }                                       


  
    private void txt_veterinario_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_veterinario_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_veterinario_nomeActionPerformed

    private void tab_veterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_veterinarioMouseClicked
        int linha = tab_veterinario.getSelectedRow();
        String valor = String.valueOf(tab_veterinario.getValueAt(linha, 0));
        int veterinarioID = Integer.valueOf(valor);
        veterinarioDao.consultarVeterinarioID(veterinarioID, txt_veterinario_id, txt_veterinario_animal, txt_veterinario_nome, jdate_veterinario_inicio, jdate_veterinario_termino, txt_veterinario_diagnostico, txt_veterinario_tratamento, txt_veterinario_valor, this);
        btn_veterinario_cadastrar.setEnabled(false);
        btn_veterinario_excluir.setEnabled(true);
        btn_veterinario_alterar.setEnabled(true);
        sem_animal_veterinario.setText("");
        sem_animal_veterinario.setText("");
    }//GEN-LAST:event_tab_veterinarioMouseClicked

    private void btn_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar2ActionPerformed
        veterinarioDao.consultarVeterinario(txt_veterinario_pesquisa, tab_veterinario, this);
        txt_veterinario_animal.setText("");
        txt_veterinario_nome.setText("");
        txt_veterinario_id.setText("");
        jdate_veterinario_inicio.setCalendar(null);
        jdate_veterinario_termino.setCalendar(null);
        txt_veterinario_diagnostico.setText("");
        txt_veterinario_tratamento.setText("");
        txt_veterinario_valor.setText("0.00");
        btn_veterinario_cadastrar.setEnabled(true);
        btn_veterinario_excluir.setEnabled(false);
        btn_veterinario_alterar.setEnabled(false);
        sem_animal_veterinario.setText("");
        sem_animal_veterinario.setText("");
    }//GEN-LAST:event_btn_buscar2ActionPerformed

    private void txt_veterinario_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_veterinario_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_veterinario_valorActionPerformed

    private void btn_veterinario_cadastrarAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btn_veterinario_cadastrarAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_veterinario_cadastrarAncestorMoved

    private void btn_veterinario_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veterinario_cadastrarActionPerformed
        String nome = jnome.getText();
        String how = txt_veterinario_animal.getText();
        veterinario.setVeterinario_animal(txt_veterinario_animal.getText());
        veterinario.setVeterinario_nome(txt_veterinario_nome.getText());
        java.sql.Date date_veterinario_inicio = new java.sql.Date(jdate_veterinario_inicio.getDate().getTime());
        veterinario.setVeterinario_inicio(date_veterinario_inicio);

        java.sql.Date date_veterinario_termino = new java.sql.Date(jdate_veterinario_termino.getDate().getTime());
        veterinario.setVeterinario_termino(date_veterinario_termino);
        veterinario.setVeterinario_diagnostico(txt_veterinario_diagnostico.getText());
        veterinario.setVeterinario_tratamento(txt_veterinario_tratamento.getText());
        veterinario.setVeterinario_valor(Float.valueOf(txt_veterinario_valor.getText()));

        if (!"".equals(txt_veterinario_animal.getText())) {
            if (!"".equals(txt_veterinario_nome.getText())) {
                veterinarioDao.salvarVeterinario(veterinario, nome, how, this);
                veterinarioDao.consultarVeterinario(txt_veterinario_pesquisa, tab_veterinario, this);
                txt_veterinario_animal.setText("");
                txt_veterinario_nome.setText("");
                jdate_veterinario_inicio.setCalendar(null);
                jdate_veterinario_termino.setCalendar(null);
                txt_veterinario_diagnostico.setText("");
                txt_veterinario_tratamento.setText("");
                txt_veterinario_valor.setText("0.00");
                sem_animal_veterinario.setText("");
                sem_veterinario_veterinario.setText("");
            } else {
                sem_veterinario_veterinario.setText("Campo obrigatório");
            }

        } else {
            sem_animal_veterinario.setText("Campo obrigatório");
        }
    }//GEN-LAST:event_btn_veterinario_cadastrarActionPerformed

    private void btn_veterinario_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veterinario_excluirActionPerformed
        String nome = jnome.getText();
        String how = txt_veterinario_animal.getText();
        veterinario.setVeterinario_id(Integer.valueOf(txt_veterinario_id.getText()));
        veterinarioDao.apagarVeterinario(veterinario, nome, how, this);
        veterinarioDao.consultarVeterinario(txt_veterinario_pesquisa, tab_veterinario, this);

        txt_veterinario_id.setText("");
        txt_veterinario_animal.setText("");
        txt_veterinario_nome.setText("");
        jdate_veterinario_inicio.setCalendar(null);
        jdate_veterinario_termino.setCalendar(null);
        txt_veterinario_diagnostico.setText("");
        txt_veterinario_tratamento.setText("");
        txt_veterinario_valor.setText("0.00");
    }//GEN-LAST:event_btn_veterinario_excluirActionPerformed

    private void btn_veterinario_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veterinario_alterarActionPerformed
        String nome = jnome.getText();
        String how = txt_veterinario_animal.getText();
        veterinario.setVeterinario_id(Integer.valueOf(txt_veterinario_id.getText()));
        veterinario.setVeterinario_animal(txt_veterinario_animal.getText());
        veterinario.setVeterinario_nome(txt_veterinario_nome.getText());
        java.sql.Date date_veterinario_inicio = new java.sql.Date(jdate_veterinario_inicio.getDate().getTime());
        veterinario.setVeterinario_inicio(date_veterinario_inicio);

        java.sql.Date date_veterinario_termino = new java.sql.Date(jdate_veterinario_termino.getDate().getTime());
        veterinario.setVeterinario_termino(date_veterinario_termino);
        veterinario.setVeterinario_diagnostico(txt_veterinario_diagnostico.getText());
        veterinario.setVeterinario_tratamento(txt_veterinario_tratamento.getText());
        veterinario.setVeterinario_valor(Float.valueOf(txt_veterinario_valor.getText()));

        if (!"".equals(txt_veterinario_animal.getText())) {
            if (!"".equals(txt_veterinario_nome.getText())) {
                veterinarioDao.alterarVeterinario(veterinario, nome, how, this);
                veterinarioDao.consultarVeterinario(txt_veterinario_pesquisa, tab_veterinario, this);
                txt_veterinario_animal.setText("");
                txt_veterinario_nome.setText("");
                jdate_veterinario_inicio.setCalendar(null);
                jdate_veterinario_termino.setCalendar(null);
                txt_veterinario_diagnostico.setText("");
                txt_veterinario_tratamento.setText("");
                txt_veterinario_valor.setText("0.00");
                sem_animal_veterinario.setText("");
                sem_animal_veterinario.setText("");
            } else {
                sem_animal_veterinario.setText("Campo obrigatório");
            }

        } else {
            sem_animal_veterinario.setText("Campo obrigatório");
        }
    }//GEN-LAST:event_btn_veterinario_alterarActionPerformed

    private void homeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homeComponentShown

     
    }//GEN-LAST:event_homeComponentShown


  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Veterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jveterinario;
    private javax.swing.JButton btn_animais;
    private javax.swing.JButton btn_animais1;
    private javax.swing.JButton btn_buscar2;
    private javax.swing.JButton btn_calendario;
    private javax.swing.JButton btn_celeiro;
    private javax.swing.JButton btn_ferrajamento;
    private javax.swing.JButton btn_financeiro;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_pastagem;
    private javax.swing.JButton btn_rh;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton btn_usuario1;
    private javax.swing.JButton btn_veterinario;
    private javax.swing.JButton btn_veterinario_alterar;
    private javax.swing.JButton btn_veterinario_cadastrar;
    private javax.swing.JButton btn_veterinario_excluir;
    private javax.swing.JTabbedPane home;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jdata;
    private com.toedter.calendar.JDateChooser jdate_veterinario_inicio;
    private com.toedter.calendar.JDateChooser jdate_veterinario_termino;
    private javax.swing.JTextField jnome;
    private javax.swing.JLabel sem_animal_veterinario;
    private javax.swing.JLabel sem_veterinario_veterinario;
    private javax.swing.JTable tab_veterinario;
    private javax.swing.JTextField txt_veterinario_animal;
    private javax.swing.JTextArea txt_veterinario_diagnostico;
    private javax.swing.JTextField txt_veterinario_id;
    private javax.swing.JTextField txt_veterinario_nome;
    private javax.swing.JTextField txt_veterinario_pesquisa;
    private javax.swing.JTextArea txt_veterinario_tratamento;
    private javax.swing.JTextField txt_veterinario_valor;
    // End of variables declaration//GEN-END:variables
}
